#+STARTUP: showall

* 异步
** 功能
异步处理特性可以应用于 Servlet 和过滤器两种组件
** 异步配置
*** 部署文件启用servlet
<servlet>和<filter>标签增加了<async-supported>子标签，该标签的默认取值为 false，要启用异步处理支持，则将其设为true
例如,
<servlet> 
    <servlet-name>DemoServlet</servlet-name> 
    <servlet-class>footmark.servlet.Demo Servlet</servlet-class> 
    <async-supported>true</async-supported> 
</servlet>
*** 注解启用servlet
@WebServlet 和 @WebFilter asyncSupported属性
@WebFilter(urlPatterns = "/demo",asyncSupported = true) 
public class DemoFilter implements Filter{...}

属性名	类型	描述
name	String	指定 Servlet 的 name 属性，等价于 <servlet-name>。如果没有显式指定，则该 Servlet 的取值即为类的全限定名。
value	String[]	该属性等价于 urlPatterns 属性。两个属性不能同时使用。
urlPatterns	String[]	指定一组 Servlet 的 URL 匹配模式。等价于 <url-pattern> 标签。
loadOnStartup	int	指定 Servlet 的加载顺序，等价于 <load-on-startup> 标签。
initParams	WebInitParam[]	指定一组 Servlet 初始化参数，等价于 <init-param> 标签。
asyncSupported	boolean	声明 Servlet 是否支持异步操作模式，等价于 <async-supported> 标签。
description	String	该 Servlet 的描述信息，等价于 <description> 标签。
displayName	String	该 Servlet 的显示名，通常配合工具使用，等价于 <display-name> 标签。
*** metadata-complete
web.xml 的顶层标签 <web-app> 有一个 metadata-complete 属性
如果设置为 true，则容器在部署时将只依赖部署描述文件，忽略所有的注解（同时也会跳过 web-fragment.xml 的扫描，亦即禁用可插性支持.
如果不配置该属性，或者将其设置为 false，则表示启用注解支持（和可插性支持）
** 原理

** 示例


* 注解
** 实现原理


* 插件
** 实现原理


* 参考
http://www.ibm.com/developerworks/cn/java/j-lo-servlet30/
http://www.ibm.com/developerworks/cn/java/j-lo-servlet/


