#+STARTUP: showall

#+include: "catalog.org"

* 基础
*概述*
# TODO
** 关于/bin/sh
shell是unix系统最重要的部分之一。shell是运行命令的程序。例，shell的职责之一是运行用户键入的命令。shell也作为一个小的编程环境。
Unix程序员通常依赖shell将任务分成小的组件去执行、合并结果。

系统的很多重要部分实际上是shell脚本（包含shell命令的文本）。如果你用MS-DOS，shell脚本类似 *.BAT* 文件但更加强大。第七章将简单介绍
shell脚本，你可以在完成本章后细读它。

当你读完本书，你将学会如何用shell使用命令。关于shell最棒的一件事是如果你写错了，可以看到你输入的什么，哪里出错了，然后快速的重试一下。
不要害怕尝试新的东西，学习shell的唯一方式就是去使用它。

有很多不同的unix shell，但它们的功能大部分来源于Bourne shell,*/bin/sh* 。通过本书你将看到每一个Unix系统需要Bourne shell去正常地工作。

linux用加强版本的sh，叫做bash，the "Bourne-again" shell。对于大部分的linux发行版，bash是默认的shell，在linux系统上 */bin/sh*
常常是某个bash的连接。当运行本书里的例子时你应该使用 *bash* shell。

当你是在某个机构里用一个非管理员帐号时，你可能没有 *bash* 。你可以用chsh改变你的shell，或找系统管理员帮助

** 使用Shell
安装linux后，你已经设置了root密码，希望最好给自己创建一个普通账户。这章节你应该使用普通用户登录。

登录后你首先需要启动一个shell窗口。shell启动后，可以看到在窗口的上方包含一个提示符，它通常以'$'结尾。在Red Hat Linux，提示符类似[name@host path]$。
若你使用windows，你会发现shell窗口很像命令提示符。

#+BEGIN_EXAMPLE
   *注意* 你或许听到过称终端窗口为shell窗口。终端窗口是用户接口的一部分，它从windows系统接收按键，然后在屏幕上绘制字符。你可以把终端当成shell和用户之间的中间人。
#+END_EXAMPLE

现在输入命令然后按回车:
*cat /etc/passwd*

这个命令输出很多用户名开头的行，然后输出shell提示符。如果输出的文字读着不舒服，修改你喜欢的字体设置。
   
** 基本命令
** 使用目录命令
** 中级命令
** 改变用户密码和Shell
** 点开头的文件
** 环境和Shell变量
** 命名路径
** 特殊字符
** 命令行编辑
** 文本编辑器
** 获取在线帮助
** Shell的输入和输出
** 理解错误消息
** 进程
** 文件模式和权限
** 存档和压缩文件


# 

