#+STARTUP: showall

* top
Hot Key	Usage
t	Displays summary information off and on.
m	Displays memory information off and on.
A	Sorts the display by top consumers of various system resources. Useful for quick identification of performance-hungry tasks on a system.
f	Enters an interactive configuration screen for top. Helpful for setting up top for a specific task.
o	Enables you to interactively select the ordering within top.
r	Issues renice command.
k	Issues kill command.
z	Turn on or off color/mono

* vmstat

* iostat

* curl
** 命令
- 下载网页
curl -o save.html http://url
- 设置代理-x 123.45.67.89:1080
- cookie处理
-D cookie0002.txt -b cookie0001.txt
- 指定浏览器
-A "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0)" 
- post数据
curl -d "k=v&k=v" "url"

** 参考
http://baike.baidu.com/view/1326315.htm

* w
w command displays information about the users currently on the machine, and their processes.
w usr

* uptime
how long the server has been running

* ps
ps -A or -e
Print A Process Tree
# ps -ejH
# ps axjf
# pstree
Display Only The Process IDs of Lighttpd
# ps -C lighttpd -o pid=
pgrep lighttpd
Find Out The Top 10 Memory Consuming Process
# ps -auxf | sort -nr -k 4 | head -10
Find Out top 10 CPU Consuming Process
# ps -auxf | sort -nr -k 3 | head -10

* free

* sar 
- Collect and Report System Activity
To see network counter, enter:
# sar -n DEV | more
To display the network counters from the 24th:
# sar -n DEV -f /var/log/sa/sa24 | more
sar 4 5

* mpstat
displays activities for each available processor
mpstat -P ALL

* pmap - Process Memory Usage
pmap -d PID
mapped: 933712K total amount of memory mapped to files
writeable/private: 4304K the amount of private address space
shared: 768000K the amount of address space this process is sharing with others

* netstat and ss - Network Statistics
netstat displays network connections, routing tables, interface statistics, masquerade connections, and multicast memberships.
ss command is used to dump socket statistics

* iptraf - Real-time Network Statistics

* tcpdump - Detailed Network Traffic Analysis
tcpdump -i eth1 'udp port 53'
tcpdump 'tcp port 80 and (((ip[2:2] - ((ip[0]&0xf)<<2)) - ((tcp[12]&0xf0)>>2)) != 0)'
tcpdump -i eth1 'dst 202.54.1.5 and (port 21 or 20'
tcpdump -ni eth0 'dst 192.168.1.5 and tcp and port http'
Use wireshark to view detailed information about files, enter:
# tcpdump -n -i eth1 -s 0 -w output.txt src or dst port 80

* strace - System Calls

* nmap - scan your server for open ports.

* lsof - list open files, network connections and much more.

* ntop web based tool

* vnstat - vnStat is a console-based network traffic monitor.
It keeps a log of hourly, daily and monthly network traffic for the selected interface(s).

* 


Nagios
Cacti









